# Generated by Django 4.2 on 2023-04-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dislike',
        ),
    ]
